include:
  - project: "waldur/waldur-pipelines"
    file: "/templates/stages.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/release/publish.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/release/python-module-release.yml"

.Test template:
  stage: test
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  script:
    - source ${TESTS_DIR}/.env.rc
    - cp ./config-components.yaml.example ./config-components.yaml
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install
    - pytest --junitxml=report.xml --cov=waldur_slurm/ $TESTS_DIR
    - coverage xml
    - coverage report

.Run linters template:
  stage: test
  interruptible: true
  rules:
    # Skip tests if specified
    - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    # If tagged release
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
    # If event is related to a created merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - pip install pre-commit
    - pre-commit run --all

.Test SLURM to Waldur sync template:
  extends: .Test template
  variables:
    TESTS_DIR: "tests/test_slurm_to_waldur"

.Test Waldur to SLURM sync template:
  extends: .Test template
  variables:
    TESTS_DIR: "tests/test_waldur_to_slurm"

Publish python module tagged release:
  image: python:3.9-alpine
  before_script:
    - source tests/test_waldur_to_slurm/.env.rc
    - cp ./config-components.yaml.example ./config-components.yaml
  script:
    - pip install poetry
    - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
    - poetry publish --build

Run python v3.9 linters:
  image: "registry.hpc.ut.ee/mirror/library/python:3.9"
  extends: .Run linters template
  before_script:
    - |
      echo 'default_language_version:' >> .pre-commit-config.yaml
      echo '  python: python3.9' >> .pre-commit-config.yaml
    - cat .pre-commit-config.yaml

Run python v3.10 linters:
  image: "registry.hpc.ut.ee/mirror/library/python:3.10"
  extends: .Run linters template
  before_script:
    - |
      echo 'default_language_version:' >> .pre-commit-config.yaml
      echo '  python: python3.10' >> .pre-commit-config.yaml
    - cat .pre-commit-config.yaml

Run python v3.11 linters:
  image: "registry.hpc.ut.ee/mirror/library/python:3.11"
  extends: .Run linters template
  before_script:
    - |
      echo 'default_language_version:' >> .pre-commit-config.yaml
      echo '  python: python3.11' >> .pre-commit-config.yaml
    - cat .pre-commit-config.yaml

Run python v3.9 tests (Waldur to SLURM):
  image: "registry.hpc.ut.ee/mirror/library/python:3.9"
  extends: .Test Waldur to SLURM sync template

Run python v3.10 tests (Waldur to SLURM):
  image: "registry.hpc.ut.ee/mirror/library/python:3.10"
  extends: .Test Waldur to SLURM sync template

Run python v3.11 tests (Waldur to SLURM):
  image: "registry.hpc.ut.ee/mirror/library/python:3.11"
  extends: .Test Waldur to SLURM sync template

Run python v3.9 tests (SLURM to Waldur):
  image: "registry.hpc.ut.ee/mirror/library/python:3.9"
  extends: .Test SLURM to Waldur sync template

Run python v3.10 tests (SLURM to Waldur):
  image: "registry.hpc.ut.ee/mirror/library/python:3.10"
  extends: .Test SLURM to Waldur sync template

Run python v3.11 tests (SLURM to Waldur):
  image: "registry.hpc.ut.ee/mirror/library/python:3.11"
  extends: .Test SLURM to Waldur sync template

Upload docs:
  image:
    name: registry.hpc.ut.ee/mirror/alpine/git:v2.30.2
    entrypoint: [""]
  stage: deploy
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "schedule"'
  script:
    - cd /tmp/
    - git clone "https://gitlab-ci-token:$GITLAB_TOKEN@$CI_SERVER_HOST/waldur/waldur-docs.git"
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - cd waldur-docs/
    - ls docs/admin-guide/providers/
    - cp -v $CI_PROJECT_DIR/README.md docs/admin-guide/providers/remote-slurm.md
    - mkdir docs/admin-guide/providers/examples || true
    - cp -rv $CI_PROJECT_DIR/examples/* docs/admin-guide/providers/examples/
    - cp -rv $CI_PROJECT_DIR/img/* docs/admin-guide/providers/img/
    - git add docs/admin-guide/providers/
    - git commit -m 'Update Waldur SLURM Service docs' || exit 0
    - git branch new-slurm-service-docs
    - git push --set-upstream origin new-slurm-service-docs:master
