include:
  - project: "waldur/waldur-pipelines"
    file: "/templates/stages.yml"

.Test template:
  image: registry.hpc.ut.ee/mirror/library/python:3.8
  stage: test
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml
  script:
    - source ${TESTS_DIR}/.env.rc
    - pip install -r requirements-dev.txt
    - pytest --junitxml=report.xml --cov=waldur_slurm/ $TESTS_DIR
    - coverage xml
    - coverage report

Test SLURM to Waldur sync:
  extends: .Test template
  variables:
    TESTS_DIR: "tests/test_slurm_to_waldur"

Test Waldur to SLURM sync:
  extends: .Test template
  variables:
    TESTS_DIR: "tests/test_waldur_to_slurm"
