cpu: # Type of tres with possible 'gres/' prefix
  limit: 16000  # Raw measure unit is CPU-minutes
  measured_unit: 'k-Hours' # Unit for billing
  accounting_type: usage # Can be usage or limit
  label: CPU # A label for a component in Waldur
gres/gpu:
  limit: 400  # Raw measure unit is GPU-minutes
  measured_unit: 'k-Hours' # Unit for billing
  accounting_type: usage # Can be usage or limit
  label: GPU # A label for a component in Waldur
mem:
  limit: 102400000  # Measured unit is MB-h
  measured_unit: 'gb-Hours'
  accounting_type: usage # Can be usage or limit
  label: RAM # A label for a component in Waldur
